name: Compile and Build Sass

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Sass Build
      uses: gha-utilities/sass-build@v0.5.1
      with:
        source: ./assets/sass/main.scss
        destination: ./assets/css/main.css
    
