name: Compile and Build Sass

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node- version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version:${{ matrix.node-version }}

    - name: Sass Build
  # You may pin to the exact commit or the version.
  # uses: gha-utilities/sass-build@a890a939b8c2b0778ea706fb091da0f1c6f38f92
  uses: gha-utilities/sass-build@v0.5.1
  with:
    # Relative path(s) to SASS or SCSS file, eg. _scss/main.scss
    source: ./assets/sass/main.scss
    # Path(s) compiled CSS should be saved, eg. ~/workspace_sass/assets/css/main.css
    destination: ./assets/css/main.css
    
